SELECT * FROM CHARGE WHERE TRAIN_CLASS_NO = 'K';

UPDATE charge SET PRICE_NORMAL = 1000 WHERE TRAIN_CLASS_NO = K AND END_STATION = 001 AND START_STATION = 003;

-- 열차번호, 출발시각, 출발역, 도착역 --도착시간 추가?
SELECT *
  FROM LINE_TIME;

--열차번호
SELECT TRAIN_NO
  FROM TRAIN;

--출발시각
SELECT START_TIME
  FROM LINE_TIME;
  
--역이름
SELECT STATION_NAME
  FROM STATION;

--출발역
--도착역


SELECT A.TRAIN_NO, B.START_TIME, C.STATION_NAME, D.STATION_NAME
  FROM TRAIN A, LINE_TIME B, STATION C, STATION D, LINE_ROUTE E
 WHERE A.TRAIN_NO = B.LINE_NO
   AND C.STATION_NO = E.START_STATION
   AND D.STATION_NO = E.END_STATION
 --  AND A.LINE_NO = E.LINE_NO
   AND B.LINE_NO = E.LINE_NO;

  
--   
SELECT A.LINE_NO, B.STATION_NAME START_STATION, C.STATION_NAME END_STATION, A.STATION_ORDER, A.TIME_ENROUTE
  FROM LINE_ROUTE A, STATION B, STATION C
 WHERE B.STATION_NO = A.START_STATION
   AND C.STATION_NO = A.END_STATION
   AND A.LINE_NO = 'M1351'
 ORDER BY A.STATION_ORDER;
 

 
 